### ISSUE TITLE
Disable URL fragments?

### ISSUE THREAD

**Issue by dennisfrank** [nico3333fr/jquery-accessible-tabs-aria#18]
Is it possible to disable URL fragments?

URL fragments can interfere with the back button. If you went through some tabs you need the the same amount of clicks/tabs to navigate to the previous page via the browser back button. Also, not every user understands URL fragments when copying URLs from the URL bar.

I can imagine that for some sites/pages it makes a lot of sense to utilize URL fragments on others not so much.

**Comment by nico3333fr** [comment]
Hi @dennisfrank 

well, I have the issue for the moment that if the back button is used, the tabs are not updating themselves (I did not manage to find how setting up a "listener" for it), however the benefits are still more important than the problems, so that is why I kept them. :)

Well, this might be an option to add.

Thanks for the idea,
Nicolas

**Comment by nico3333fr** [comment]
Hi @dennisfrank 

the option has been added in last commits, and in the doc.

I hope you don't mind, I've mentionned your request on the plugin page https://a11y.nicolas-hoffmann.net/tabs/ 

Thanks for the suggestion again 👍

**Comment by dennisfrank** [comment]
@nico3333fr Awesome! Thank you! :smiley:
